spring.application.name=devoirexam2

spring.datasource.url=jdbc:mysql://172.20.17.143:3306/TP_DATABASE_CREATE?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8089
spring.mvc.format.date=yyyy-MM-dd
management.endpoints.web.exposure.include=prometheus,health,info